services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: meraj
      POSTGRES_PASSWORD: steven8
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: